// Barrel único de componentes UI — importa desde '@/components/ui'
export { Button } from './Button'
export { Input } from './Input'
export { Select } from './Select'
export { Modal } from './Modal'
export { Badge } from './Badge'
export { Table } from './Table'
export { Spinner, PageLoader } from './Spinner'
export { Textarea } from './Textarea'
export { toast, ToastContainer } from './Toast'
export { Pagination } from './Pagination'
export { StatCard } from './StatCard'
export { ConfirmDialog } from './ConfirmDialog'
